// See https://aka.ms/new-console-template for more information

Console.ForegroundColor = ConsoleColor.DarkRed;
Console.WriteLine("Style - Taylor Swift");
Console.ResetColor();
Console.WriteLine(@"Midnight");
Console.WriteLine("You come and pick me up, no headlights");
Console.WriteLine("Long drive");
Console.WriteLine("Could end in burning flames or paradise");
Console.WriteLine("Fade into view, oh");
Console.WriteLine("It's been a while since I have even heard from you (heard from you)");
Console.WriteLine("And I should just tell you to leave 'cause I");
Console.WriteLine("Know exactly where it leads, but I");
Console.WriteLine("Watch us go 'round and 'round each time");
Console.ForegroundColor = ConsoleColor.DarkYellow;
Console.WriteLine("You got that James Dean daydream look in your eye");
Console.WriteLine("And I got that red lip classic thing that you like");
Console.WriteLine("And when we go crashing down, we come back every time");
Console.WriteLine("'Cause we never go out of style, we never go out of style");
Console.WriteLine("You got that long hair, slicked back, white T-shirt");
Console.WriteLine("And I got that good girl faith and a tight little skirt");
Console.WriteLine("And when we go crashing down, we come back every time");
Console.WriteLine("'Cause we never go out of style, we never go out of style");
Console.ResetColor();
Console.WriteLine("So it goes");
Console.WriteLine("He can't keep his wild eyes on the road, mm");
Console.WriteLine("Takes me home");
Console.WriteLine("The lights are off, he's taking off his coat, mm, yeah");
Console.WriteLine("I say, 'I heard, oh");
Console.WriteLine("That you've been out and about with some other girl, some other girl'");
Console.WriteLine("He says, 'What you heard is true, but I");
Console.WriteLine("Can't stop thinkin' 'bout you and I'");
Console.WriteLine("I said, 'I've been there too a few times'");
Console.ForegroundColor = ConsoleColor.DarkYellow;
Console.WriteLine("'Cause you got that James Dean daydream look in your eye");
Console.WriteLine("And I got that red lip classic thing that you like");
Console.WriteLine("And when we go crashing down, we come back every time");
Console.WriteLine("'Cause we never go out of style, we never go out of style");
Console.WriteLine("You got that long hair, slicked back, white T-shirt");
Console.WriteLine("And I got that good girl faith and a tight little skirt (a tight little skirt)");
Console.WriteLine("And when we go crashing down, we come back every time");
Console.WriteLine("'Cause we never go out of style (we never go), we never go out of style");
Console.ResetColor();
Console.WriteLine("Take me home");
Console.WriteLine("Just take me home");
Console.WriteLine("Yeah, just take me home");
Console.WriteLine("Oh, whoa, oh");
Console.WriteLine("(Out of style)");
Console.ForegroundColor = ConsoleColor.DarkYellow;
Console.WriteLine("Oh, you got that James Dean daydream look in your eye");
Console.WriteLine("And I got that red lip classic thing that you like");
Console.WriteLine("And when we go crashing down (now we go), we come back every time");
Console.WriteLine("'Cause we never go out of style, we never go out of style");
Console.ResetColor();